Test
Schleifner/eslint-assemblyscript-parser pull request #2
Opened 2023-10-31 02:14 UTC by KKiiim

2023-10-31 03:11 UTC, Changqing-JING requested changes

2023-10-31 03:11 UTC, Changqing-JING commented on asParser.cjs
> +  for (let i = 0; i < text.length; i++) {
refactor to a class using getNextChar

2023-10-31 06:56 UTC, Changqing-JING requested changes

2023-10-31 06:56 UTC, Changqing-JING commented on src/asParser.cjs
> +    this.newCode = "";
don't need to be class member

2023-10-31 06:56 UTC, Changqing-JING commented on src/asParser.cjs
> +      if(tmpC == "\n" || tmpC == " "){
consider also tab

2023-10-31 06:56 UTC, Changqing-JING commented on package.json
> +    "lint": "npx prettier . --write && eslint --ext .js,.vue --fix && npx prettier . --check"
no npx prettier . --write
no vue
no npx prettier . --check

2023-10-31 06:59 UTC, Changqing-JING requested changes

2023-10-31 06:59 UTC, Changqing-JING commented on tsconfig.json
> +    "target": "ES2021" /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */,
remove this file

2023-10-31 07:04 UTC, Changqing-JING commented on package.json
> +    "@types/chai": "^4.3.9",
cleanup unnecessary deps

2023-11-02 06:23 UTC, Changqing-JING requested changes

2023-11-02 06:23 UTC, Changqing-JING commented on testfile/exports-lazy.ts
> +@lazy export const lazyGlobalUnused: i32[] = [1,2,3];
move testfile to tests folder

2023-11-02 07:40 UTC, Changqing-JING requested changes

2023-11-02 07:40 UTC, Changqing-JING commented on .npmignore
> +README.md
remove readme

2023-11-02 09:55 UTC, Changqing-JING requested changes

2023-11-02 09:55 UTC, Changqing-JING commented on package.json
> +    "test": "mocha tests/asfileTest.cjs",
run all tests under tests folder with mocha

2023-11-02 10:27 UTC, Changqing-JING approved these changes

2023-11-03 02:35 UTC, XMadrid approved these changes

2023-11-03 02:36 UTC, merged